import type {
  AuthUser,
  Customer,
  Product,
  Groomer,
  Booking,
  AvailableStore,
} from "./types"

// --- Auth Users (for login) ---
export const authUsers: AuthUser[] = [
  { id: "admin-1", name: "Admin Paswhip", email: "admin@pawship.com", role: "admin" },
  { id: "groomer-1", name: "Sarah Miller", email: "sarah@pawship.com", role: "groomer" },
  { id: "groomer-2", name: "Jake Thompson", email: "jake@pawship.com", role: "groomer" },
  { id: "cust-1", name: "Andi Pratama", email: "andi@email.com", role: "customer" },
  { id: "cust-2", name: "Siti Rahayu", email: "siti@email.com", role: "customer" },
]

// --- Stores ---
export const mockStores: AvailableStore[] = [
  {
    id: "store-jakarta-selatan",
    name: "Pawship Kemang",
    city: "Jakarta Selatan",
    address: "Jl. Kemang Raya No. 88, Jakarta Selatan",
    whatsapp: "6281234560001",
  },
  {
    id: "store-jakarta-pusat",
    name: "Pawship Sudirman",
    city: "Jakarta Pusat",
    address: "Jl. Sudirman No. 45, Jakarta Pusat",
    whatsapp: "6281234560002",
  },
  {
    id: "store-jakarta-barat",
    name: "Pawship Puri",
    city: "Jakarta Barat",
    address: "Jl. Puri Indah No. 12, Jakarta Barat",
    whatsapp: "6281234560003",
  },
]

// --- Products / Services ---
export const products: Product[] = [
  {
    id: "svc-1",
    code: "GRM-BASIC",
    name: "Basic Grooming",
    description: "Perawatan dasar yang bikin pawfriends bersih, wangi, dan nyaman lagi. Cocok untuk rutin supaya tetap fresh dan sehat.",
    category: "grooming",
    price: 120000,
    prices: [
      { sizeId: "size-small", sizeName: "Small (< 5 kg)", price: 120000 },
      { sizeId: "size-medium", sizeName: "Medium (5–10 kg)", price: 150000 },
      { sizeId: "size-large", sizeName: "Large (10–20 kg)", price: 200000 },
      { sizeId: "size-xlarge", sizeName: "Extra Large (> 20 kg)", price: 250000 },
    ],
    duration: 60,
    petTypes: ["dog", "cat"],
    sizeCategories: ["small", "medium", "large", "extra-large"],
    isActive: true,
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop&auto=format",
    includes: [
      "Mandi bersih dengan shampoo gentle khusus anabul",
      "Blow dry sampai kering dan fluffy",
      "Gunting kuku & bersihin telinga",
      "Pembersihan telinga",
      "Cukur area paw (bawah kaki)",
      "Parfum pet friendly",
    ],
    availableStores: mockStores,
  },
  {
    id: "svc-2",
    code: "GRM-FULL",
    name: "Full Grooming",
    description: "Buat pawfriends yang mau total glow up. Bersihnya dapet, rapinya dapet, tampilannya juga makin pawfect.",
    category: "grooming",
    price: 200000,
    prices: [
      { sizeId: "size-small", sizeName: "Small (< 5 kg)", price: 200000 },
      { sizeId: "size-medium", sizeName: "Medium (5–10 kg)", price: 240000 },
      { sizeId: "size-large", sizeName: "Large (10–20 kg)", price: 300000 },
      { sizeId: "size-xlarge", sizeName: "Extra Large (> 20 kg)", price: 370000 },
    ],
    duration: 90,
    petTypes: ["dog", "cat"],
    sizeCategories: ["small", "medium", "large", "extra-large"],
    isActive: true,
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&h=400&fit=crop&auto=format",
    includes: [
      "Mandi bersih dengan shampoo gentle khusus anabul",
      "Blow dry sampai kering dan fluffy",
      "Gunting kuku & bersihin telinga",
      "Cukur paw & area higienis",
      "Trimming / styling bulu sesuai request pawrents",
      "Parfum pet friendly",
    ],
    availableStores: mockStores,
  },
  {
    id: "svc-3",
    code: "HOME-BASIC",
    name: "Home Grooming – Basic",
    description: "Buat pawfriends yang lebih nyaman grooming di rumah. Kami datang dengan peralatan lengkap, jadi anabul tetap tenang di lingkungan yang familiar.",
    category: "grooming",
    price: 180000,
    prices: [
      { sizeId: "size-small", sizeName: "Small (< 5 kg)", price: 180000 },
      { sizeId: "size-medium", sizeName: "Medium (5–10 kg)", price: 220000 },
      { sizeId: "size-large", sizeName: "Large (10–20 kg)", price: 280000 },
      { sizeId: "size-xlarge", sizeName: "Extra Large (> 20 kg)", price: 340000 },
    ],
    duration: 75,
    petTypes: ["dog", "cat"],
    sizeCategories: ["small", "medium", "large", "extra-large"],
    isActive: true,
    image: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=600&h=400&fit=crop&auto=format",
    includes: [
      "Mandi bersih dengan shampoo premium, lebih fluffy dan lembut",
      "Blow dry sampai kering dan fluffy",
      "Gunting kuku & bersihin telinga",
      "Pembersihan telinga",
      "Cukur area paw (bawah kaki)",
      "Parfum pet friendly",
    ],
    availableStores: mockStores,
  },
  {
    id: "svc-4",
    code: "HOME-FULL",
    name: "Home Grooming – Full Service",
    description: "Glow up lengkap tanpa perlu pergi ke mana-mana. Cocok buat pawfriends yang butuh rapih total tapi tetap mau di rumah.",
    category: "grooming",
    price: 280000,
    prices: [
      { sizeId: "size-small", sizeName: "Small (< 5 kg)", price: 280000 },
      { sizeId: "size-medium", sizeName: "Medium (5–10 kg)", price: 330000 },
      { sizeId: "size-large", sizeName: "Large (10–20 kg)", price: 400000 },
      { sizeId: "size-xlarge", sizeName: "Extra Large (> 20 kg)", price: 480000 },
    ],
    duration: 120,
    petTypes: ["dog", "cat"],
    sizeCategories: ["small", "medium", "large", "extra-large"],
    isActive: true,
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&h=400&fit=crop&auto=format",
    includes: [
      "Mandi bersih dengan shampoo premium, lebih fluffy dan lembut",
      "Blow dry sampai kering dan fluffy",
      "Gunting kuku & bersihin telinga",
      "Cukur paw & area higienis",
      "Trimming / styling bulu sesuai request pawrents",
      "Parfum pet friendly",
    ],
    availableStores: mockStores,
  },
  {
    id: "addon-1",
    code: "ADD-DETANG3",
    name: "3 Spots Detangling",
    description: "Buka kusut di 3 area tertentu (biasanya ketiak, belakang telinga, atau ekor) biar bulu balik halus & nggak ketarik sakit.",
    category: "addon",
    price: 35000,
    duration: 15,
    petTypes: ["dog", "cat"],
    isActive: true,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "addon-2",
    code: "ADD-DETANGFULL",
    name: "Full Body Detangling",
    description: "Untuk anabul yang kusutnya parah se-badan. Kita urai pelan-pelan dengan teknik gentle supaya tetap nyaman.",
    category: "addon",
    price: 75000,
    duration: 30,
    petTypes: ["dog", "cat"],
    isActive: true,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "addon-3",
    code: "ADD-FLEATICK-SHP",
    name: "Flea & Tick Shampoo",
    description: "Shampoo khusus bantu bersihin kutu & caplak, bikin kulit lebih sehat dan lega.",
    category: "addon",
    price: 50000,
    duration: 10,
    petTypes: ["dog", "cat"],
    isActive: true,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "addon-4",
    code: "ADD-FUNGAL",
    name: "Fungal Shampoo Treatment",
    description: "Perawatan dengan shampoo anti-jamur untuk bantu redakan masalah kulit.",
    category: "addon",
    price: 60000,
    duration: 15,
    petTypes: ["dog", "cat"],
    isActive: true,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "addon-5",
    code: "ADD-WHITE",
    name: "Whitening Shampoo",
    description: "Bikin bulu lebih cerah & bersih, cocok buat yang warna bulunya putih atau terang.",
    category: "addon",
    price: 45000,
    duration: 10,
    petTypes: ["dog", "cat"],
    isActive: true,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "addon-6",
    code: "ADD-SHAVE",
    name: "Shaving Gundul",
    description: "Cukur rapi. Fresh, clean, dan anti gerah.",
    category: "addon",
    price: 80000,
    duration: 30,
    petTypes: ["dog", "cat"],
    isActive: true,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "addon-7",
    code: "ADD-PREMSHP",
    name: "Basic Care Upgrade",
    description: "Upgrade ke shampoo premium + conditioner biar bulu lebih fluffy, lembut, dan wangi tahan lama.",
    category: "addon",
    price: 40000,
    duration: 10,
    petTypes: ["dog", "cat"],
    isActive: true,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "addon-8",
    code: "ADD-FACETRIM",
    name: "Face & Eye Trimming",
    description: "Rapihin area wajah & sekitar mata supaya lebih bersih dan nggak ganggu penglihatan.",
    category: "addon",
    price: 35000,
    duration: 15,
    petTypes: ["dog", "cat"],
    isActive: true,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "addon-9",
    code: "ADD-BODYTRIM",
    name: "Full Body Trimming",
    description: "Rapihin seluruh badan tanpa potong model, hasilnya neat & comfy.",
    category: "addon",
    price: 90000,
    duration: 30,
    petTypes: ["dog", "cat"],
    isActive: true,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "addon-10",
    code: "ADD-PAWBALM",
    name: "Paw Balm Treatment",
    description: "Oles balm di telapak kaki biar nggak kering & tetap lembut.",
    category: "addon",
    price: 30000,
    duration: 10,
    petTypes: ["dog", "cat"],
    isActive: true,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "addon-11",
    code: "ADD-FLEATICK-SPR",
    name: "Flea Tick Spray",
    description: "Semprot perlindungan tambahan anti kutu setelah grooming.",
    category: "addon",
    price: 25000,
    duration: 5,
    petTypes: ["dog", "cat"],
    isActive: true,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "addon-12",
    code: "ADD-EXTRAHANDLING",
    name: "Extra Handling",
    description: "Untuk anabul yang super aktif atau butuh perhatian ekstra selama grooming.",
    category: "addon",
    price: 50000,
    duration: 15,
    petTypes: ["dog", "cat"],
    isActive: true,
    image: "/placeholder.svg?height=400&width=600",
  },
]

// --- Groomers ---
export const groomers: Groomer[] = [
  {
    id: "groomer-1",
    name: "Sarah Miller",
    email: "sarah@pawship.com",
    phone: "081234567890",
    specialties: ["Large Dogs", "De-shedding", "Creative Grooming"],
    isActive: true,
    avatar: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "groomer-2",
    name: "Jake Thompson",
    email: "jake@pawship.com",
    phone: "081234567891",
    specialties: ["Cats", "Small Dogs", "Nail Art"],
    isActive: true,
    avatar: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "groomer-3",
    name: "Lisa Chen",
    email: "lisa@pawship.com",
    phone: "081234567892",
    specialties: ["Puppies", "Senior Pets", "Medicated Baths"],
    isActive: false,
    avatar: "/placeholder.svg?height=100&width=100",
  },
]

// --- Customers ---
export const customers: Customer[] = [
  {
    id: "cust-1",
    name: "Andi Pratama",
    email: "andi@email.com",
    phone: "081111111111",
    address: "Jl. Sudirman No. 45, Jakarta Selatan",
    area: "Jakarta Selatan",
    loyaltyPoints: 1200,
    loyaltyTier: "gold",
    notes: "Prefers morning appointments",
    createdAt: "2024-06-15",
    pets: [
      {
        id: "pet-1",
        customerId: "cust-1",
        type: "dog",
        name: "Buddy",
        breed: "Golden Retriever",
        birthday: "2021-03-10",
        weight: 30,
        sizeCategory: "large",
        notes: "Friendly but afraid of loud dryers",
        tags: ["friendly", "noise-sensitive"],
        membershipTier: "premium",
        membershipStatus: "active",
        membershipStart: "2024-01-01",
        membershipEnd: "2025-01-01",
      },
      {
        id: "pet-2",
        customerId: "cust-1",
        type: "cat",
        name: "Milo",
        breed: "Persian",
        birthday: "2022-07-20",
        weight: 4,
        sizeCategory: "small",
        notes: "Requires gentle handling",
        tags: ["gentle-handling"],
        membershipTier: "basic",
        membershipStatus: "active",
        membershipStart: "2024-06-01",
        membershipEnd: "2025-06-01",
      },
    ],
  },
  {
    id: "cust-2",
    name: "Siti Rahayu",
    email: "siti@email.com",
    phone: "081222222222",
    address: "Jl. Gatot Subroto No. 12, Jakarta Pusat",
    area: "Jakarta Pusat",
    loyaltyPoints: 450,
    loyaltyTier: "silver",
    notes: "",
    createdAt: "2024-08-20",
    pets: [
      {
        id: "pet-3",
        customerId: "cust-2",
        type: "dog",
        name: "Luna",
        breed: "Shih Tzu",
        birthday: "2023-01-15",
        weight: 5,
        sizeCategory: "small",
        notes: "Matting prone, needs regular grooming",
        tags: ["matting-prone", "regular"],
        membershipTier: "vip",
        membershipStatus: "active",
        membershipStart: "2024-08-01",
        membershipEnd: "2025-08-01",
      },
    ],
  },
  {
    id: "cust-3",
    name: "Budi Santoso",
    email: "budi@email.com",
    phone: "081333333333",
    address: "Jl. Kemang Raya No. 88, Jakarta Selatan",
    area: "Jakarta Selatan",
    loyaltyPoints: 80,
    loyaltyTier: "bronze",
    notes: "New customer",
    createdAt: "2025-01-10",
    pets: [
      {
        id: "pet-4",
        customerId: "cust-3",
        type: "dog",
        name: "Rocky",
        breed: "Pomeranian",
        birthday: "2024-05-01",
        weight: 3,
        sizeCategory: "small",
        notes: "",
        tags: [],
        membershipTier: "basic",
        membershipStatus: "active",
        membershipStart: "2025-01-10",
        membershipEnd: "2026-01-10",
      },
    ],
  },
]

// --- Bookings ---
export const bookings: Booking[] = [
  {
    id: "bk-1",
    date: "2026-02-07",
    timeStart: "09:00",
    timeEnd: "10:30",
    type: "in-store",
    customerId: "cust-1",
    customerName: "Andi Pratama",
    customerStatus: "Gold Member",
    petId: "pet-1",
    petName: "Buddy",
    requestNotes: "Please use hypoallergenic shampoo",
    status: "confirmed",
    jobStatus: "pending",
    serviceId: "svc-1",
    serviceName: "Basic Grooming",
    addOnIds: ["addon-7", "addon-8"],
    addOnNames: ["Basic Care Upgrade", "Face & Eye Trimming"],
    preConditions: [],
    groomerId: "groomer-1",
    groomerName: "Sarah Miller",
    travelFee: 0,
    media: [],
    createdAt: "2026-02-05",
  },
  {
    id: "bk-2",
    date: "2026-02-07",
    timeStart: "11:00",
    timeEnd: "11:45",
    type: "home",
    customerId: "cust-2",
    customerName: "Siti Rahayu",
    customerStatus: "Silver Member",
    petId: "pet-3",
    petName: "Luna",
    requestNotes: "Dog is nervous around strangers, please be patient",
    status: "confirmed",
    jobStatus: "pending",
    serviceId: "svc-2",
    serviceName: "Full Grooming",
    addOnIds: ["addon-10"],
    addOnNames: ["Paw Balm Treatment"],
    preConditions: [],
    groomerId: "groomer-1",
    groomerName: "Sarah Miller",
    travelFee: 50000,
    media: [],
    createdAt: "2026-02-04",
  },
  {
    id: "bk-3",
    date: "2026-02-08",
    timeStart: "10:00",
    timeEnd: "10:15",
    type: "in-store",
    customerId: "cust-3",
    customerName: "Budi Santoso",
    customerStatus: "Bronze Member",
    petId: "pet-4",
    petName: "Rocky",
    requestNotes: "",
    status: "not-confirmed",
    jobStatus: "pending",
    serviceId: "svc-3",
    serviceName: "Home Grooming – Basic",
    addOnIds: [],
    addOnNames: [],
    preConditions: [],
    groomerId: "groomer-2",
    groomerName: "Jake Thompson",
    travelFee: 0,
    media: [],
    createdAt: "2026-02-06",
  },
  {
    id: "bk-4",
    date: "2026-02-06",
    timeStart: "14:00",
    timeEnd: "15:00",
    type: "in-store",
    customerId: "cust-1",
    customerName: "Andi Pratama",
    customerStatus: "Gold Member",
    petId: "pet-2",
    petName: "Milo",
    requestNotes: "Cat dislikes water, extra gentle please",
    status: "confirmed",
    jobStatus: "started",
    serviceId: "svc-4",
    serviceName: "Home Grooming – Full Service",
    addOnIds: [],
    addOnNames: [],
    preConditions: [
      {
        id: "pc-1",
        description: "Minor skin irritation observed on left ear",
        flaggedBy: "Sarah Miller",
        flaggedAt: "2026-02-06T14:05:00",
      },
    ],
    groomerId: "groomer-1",
    groomerName: "Sarah Miller",
    travelFee: 0,
    media: [
      {
        id: "media-1",
        url: "/placeholder.svg?height=400&width=400",
        type: "before",
        uploadedAt: "2026-02-06T14:02:00",
      },
    ],
    createdAt: "2026-02-03",
  },
  {
    id: "bk-5",
    date: "2026-02-05",
    timeStart: "09:00",
    timeEnd: "09:45",
    type: "in-store",
    customerId: "cust-2",
    customerName: "Siti Rahayu",
    customerStatus: "Silver Member",
    petId: "pet-3",
    petName: "Luna",
    requestNotes: "",
    status: "completed",
    jobStatus: "finished",
    serviceId: "svc-1",
    serviceName: "Basic Grooming",
    addOnIds: ["addon-7"],
    addOnNames: ["Basic Care Upgrade"],
    preConditions: [],
    groomerId: "groomer-2",
    groomerName: "Jake Thompson",
    travelFee: 0,
    media: [
      {
        id: "media-2",
        url: "/placeholder.svg?height=400&width=400",
        type: "before",
        uploadedAt: "2026-02-05T09:00:00",
      },
      {
        id: "media-3",
        url: "/placeholder.svg?height=400&width=400",
        type: "after",
        uploadedAt: "2026-02-05T09:40:00",
      },
    ],
    createdAt: "2026-02-02",
  },
]
